#!/usr/bin/env python3
"""
Python script to plot learning evolution from C++ simulation history files.
This script reads history files generated by the C++ door learning simulation
and creates plots showing the evolution of strategy probabilities over time.
"""

import numpy as np
import matplotlib.pyplot as plt
import glob
import os
import argparse
from typing import List, Dict, Tuple
import re

class LearningHistoryPlotter:
    """
    Class to read and plot learning history from C++ simulation output files.
    """
    
    def __init__(self):
        self.history_files = []
        self.data = {}  # Dictionary to store data from multiple files
        
    def find_history_files(self, pattern: str = "learning_history_*.txt") -> List[str]:
        """
        Find all history files matching the given pattern.
        
        Args:
            pattern: Glob pattern to match history files
            
        Returns:
            List of matching file paths
        """
        self.history_files = glob.glob(pattern)
        return self.history_files
    
    def parse_history_file(self, filename: str) -> Dict:
        """
        Parse a single history file and extract data.
        
        Args:
            filename: Path to the history file
            
        Returns:
            Dictionary containing parsed data
        """
        data = {
            'filename': filename,
            'iterations': [],
            'a1': [], 'a2': [], 'a3': [], 'a4': [], 'a5': [],
            'k': None,
            'lr': None,
            'initial_probs': None
        }
        
        try:
            with open(filename, 'r') as f:
                lines = f.readlines()
            
            # Parse header information
            for line in lines:
                if line.startswith('#'):
                    # Extract k value
                    k_match = re.search(r'k=(\d+)', line)
                    if k_match:
                        data['k'] = int(k_match.group(1))
                    
                    # Extract lr value
                    lr_match = re.search(r'lr=([\d.]+)', line)
                    if lr_match:
                        data['lr'] = float(lr_match.group(1))
                    
                    # Extract initial probabilities
                    init_match = re.search(r'Initial probabilities: a1=([\d.]+), a2=([\d.]+), a3=([\d.]+), a4=([\d.]+), a5=([\d.]+)', line)
                    if init_match:
                        data['initial_probs'] = [float(x) for x in init_match.groups()]
                else:
                    # Parse data lines
                    parts = line.strip().split()
                    if len(parts) == 6:  # iteration + 5 probabilities
                        data['iterations'].append(int(parts[0]))
                        data['a1'].append(float(parts[1]))
                        data['a2'].append(float(parts[2]))
                        data['a3'].append(float(parts[3]))
                        data['a4'].append(float(parts[4]))
                        data['a5'].append(float(parts[5]))
        
        except Exception as e:
            print(f"Error reading file {filename}: {e}")
            return None
        
        return data
    
    def load_all_histories(self, file_pattern: str = "learning_history_*.txt") -> None:
        """
        Load all history files matching the pattern.
        
        Args:
            file_pattern: Glob pattern to match history files
        """
        files = self.find_history_files(file_pattern)
        
        if not files:
            print(f"No history files found matching pattern: {file_pattern}")
            return
        
        print(f"Found {len(files)} history files:")
        for f in files:
            print(f"  - {f}")
        
        for filename in files:
            data = self.parse_history_file(filename)
            if data:
                # Use filename (without extension) as key
                key = os.path.splitext(os.path.basename(filename))[0]
                self.data[key] = data
                print(f"Loaded data from {filename}: {len(data['iterations'])} iterations")
    
    def plot_single_history(self, data: Dict, save_plot: bool = True) -> None:
        """
        Plot a single history file.
        
        Args:
            data: Dictionary containing the history data
            save_plot: Whether to save the plot to file
        """
        if not data['iterations']:
            print(f"No data to plot for {data['filename']}")
            return
        
        # Create the plot
        plt.figure(figsize=(10, 6))
        
        # Define fixed colors for each strategy
        colors = {
            1: '#1f77b4',  # Blue
            2: '#ff7f0e',  # Orange  
            3: '#2ca02c',  # Green
            4: '#d62728',  # Red
            5: '#9467bd'   # Purple
        }
        
        # Plot each strategy's probability evolution
        plt.plot(data['iterations'], data['a1'], 'o-', color=colors[1], 
                label='Strategy 1 (door i on attempt i)', linewidth=2, markersize=4)
        plt.plot(data['iterations'], data['a2'], 's-', color=colors[2], 
                label='Strategy 2 (door k+1-i on attempt i)', linewidth=2, markersize=4)
        plt.plot(data['iterations'], data['a3'], '^-', color=colors[3], 
                label='Strategy 3 (always door 1)', linewidth=2, markersize=4)
        plt.plot(data['iterations'], data['a4'], 'v-', color=colors[4], 
                label='Strategy 4 (random door 1-k)', linewidth=2, markersize=4)
        plt.plot(data['iterations'], data['a5'], 'd-', color=colors[5], 
                label='Strategy 5 (prob ∝ 1/2^i)', linewidth=2, markersize=4)
        
        # Customize the plot
        plt.xlabel('Iteration', fontsize=12)
        plt.ylabel('Strategy Probability (a_i)', fontsize=12)
        
        # Create title with parameters
        title = f'Learning Evolution of Strategy Probabilities'
        if data['k'] is not None:
            title += f'\nk={data["k"]}'
        if data['lr'] is not None:
            title += f', lr={data["lr"]}'
        if data['initial_probs']:
            title += f'\nInitial: a1={data["initial_probs"][0]:.3f}, a2={data["initial_probs"][1]:.3f}, a3={data["initial_probs"][2]:.3f}, a4={data["initial_probs"][3]:.3f}, a5={data["initial_probs"][4]:.3f}'
        
        plt.title(title, fontsize=14)
        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
        plt.grid(True, alpha=0.3)
        plt.xlim(0, max(data['iterations']))
        
        # Set y-axis limits
        all_probs = data['a1'] + data['a2'] + data['a3'] + data['a4'] + data['a5']
        plt.ylim(0, max(all_probs) * 1.1)
        
        # Adjust layout to prevent legend cutoff
        plt.tight_layout()
        
        if save_plot:
            # Generate output filename
            output_filename = data['filename'].replace('.txt', '.png')
            plt.savefig(output_filename, dpi=300, bbox_inches='tight')
            print(f"Plot saved as: {output_filename}")
        
        plt.show()
    
    def plot_all_histories(self, save_plots: bool = True, show_plots: bool = True) -> None:
        """
        Plot all loaded history files.
        
        Args:
            save_plots: Whether to save plots to files
            show_plots: Whether to display plots
        """
        if not self.data:
            print("No data loaded. Call load_all_histories() first.")
            return
        
        for key, data in self.data.items():
            print(f"\nPlotting {key}...")
            self.plot_single_history(data, save_plots)
            if not show_plots:
                plt.close()
    
    def plot_combined_histories(self, save_plot: bool = True) -> None:
        """
        Plot all histories in a single figure with all lines overlaid.
        
        Args:
            save_plot: Whether to save the combined plot
        """
        if not self.data:
            print("No data loaded. Call load_all_histories() first.")
            return
        
        num_files = len(self.data)
        if num_files == 0:
            return
        
        # Create single figure with reduced width
        plt.figure(figsize=(10, 6))
        
        # Define fixed colors for each strategy
        strategy_colors = {
            1: '#1f77b4',  # Blue
            2: '#ff7f0e',  # Orange  
            3: '#2ca02c',  # Green
            4: '#d62728',  # Red
            5: '#9467bd'   # Purple
        }
        
        # Define strategy labels
        strategy_labels = ['Strategy 1 (door i on attempt i)', 
                          'Strategy 2 (door k+1-i on attempt i)',
                          'Strategy 3 (always door 1)',
                          'Strategy 4 (random door 1-k)',
                          'Strategy 5 (prob ∝ 1/2^i)']
        
        run_idx = 0
        for key, data in self.data.items():
            run_idx += 1
            
            # Plot each strategy's probability evolution with strategy-specific colors
            # All lines of the same strategy look identical
            plt.plot(data['iterations'], data['a1'], 
                    color=strategy_colors[1], linestyle='-', linewidth=2, 
                    alpha=0.8, label=strategy_labels[0] if run_idx == 1 else "")
            plt.plot(data['iterations'], data['a2'], 
                    color=strategy_colors[2], linestyle='-', linewidth=2, 
                    alpha=0.8, label=strategy_labels[1] if run_idx == 1 else "")
            plt.plot(data['iterations'], data['a3'], 
                    color=strategy_colors[3], linestyle='-', linewidth=2, 
                    alpha=0.8, label=strategy_labels[2] if run_idx == 1 else "")
            plt.plot(data['iterations'], data['a4'], 
                    color=strategy_colors[4], linestyle='-', linewidth=2, 
                    alpha=0.8, label=strategy_labels[3] if run_idx == 1 else "")
            plt.plot(data['iterations'], data['a5'], 
                    color=strategy_colors[5], linestyle='-', linewidth=2, 
                    alpha=0.8, label=strategy_labels[4] if run_idx == 1 else "")
        
        # Customize the plot
        plt.xlabel('Iteration', fontsize=12)
        plt.ylabel('Strategy Probability (a_i)', fontsize=12)
        plt.title('Learning Evolution of Strategy Probabilities - All Runs Combined', fontsize=14)
        plt.grid(True, alpha=0.3)
        
        # Set axis limits
        all_iterations = []
        all_probs = []
        for data in self.data.values():
            all_iterations.extend(data['iterations'])
            all_probs.extend(data['a1'] + data['a2'] + data['a3'] + data['a4'] + data['a5'])
        
        plt.xlim(0, max(all_iterations))
        plt.ylim(0, max(all_probs) * 1.1)
        
        # Legend is already created by the plot calls above
        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=10)
        
        plt.tight_layout()
        
        if save_plot:
            output_filename = 'combined_learning_evolution.png'
            plt.savefig(output_filename, dpi=300, bbox_inches='tight')
            print(f"Combined plot saved as: {output_filename}")
        
        plt.show()


def main():
    """Main function to run the plotting script"""
    
    parser = argparse.ArgumentParser(description='Plot learning evolution from C++ simulation history files')
    parser.add_argument('--pattern', type=str, default='learning_history_*.txt',
                       help='Pattern to match history files (default: learning_history_*.txt)')
    parser.add_argument('--combined', action='store_true',
                       help='Create a combined plot with all histories in subplots')
    parser.add_argument('--no-save', action='store_true',
                       help='Do not save plots to files')
    parser.add_argument('--no-show', action='store_true',
                       help='Do not display plots (useful for batch processing)')
    
    args = parser.parse_args()
    
    # Create plotter and load data
    plotter = LearningHistoryPlotter()
    plotter.load_all_histories(args.pattern)
    
    if not plotter.data:
        print("No history files found. Make sure to run the C++ simulation first.")
        return
    
    # Plot based on options
    if args.combined:
        print("\nCreating combined plot...")
        plotter.plot_combined_histories(save_plot=not args.no_save)
    else:
        print("\nCreating individual plots...")
        plotter.plot_all_histories(save_plots=not args.no_save, show_plots=not args.no_show)


if __name__ == "__main__":
    main()
